# Generated by Django 2.0.5 on 2018-05-03 20:54

import SmartShoppingSystem.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180503_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=SmartShoppingSystem.storage.OverwriteStorage(), upload_to='upload/images/categories'),
        ),
        migrations.AddField(
            model_name='store',
            name='cover',
            field=models.ImageField(blank=True, null=True, storage=SmartShoppingSystem.storage.OverwriteStorage(), upload_to='upload/images/stores'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=SmartShoppingSystem.storage.OverwriteStorage(), upload_to='upload/images/products/main'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, storage=SmartShoppingSystem.storage.OverwriteStorage(), upload_to='upload/images/products/thumbnails'),
        ),
    ]
