# Generated by Django 2.0.5 on 2018-06-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_beacon_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='beacons',
            field=models.ManyToManyField(blank=True, to='store.Beacon'),
        ),
        migrations.AlterField(
            model_name='store',
            name='manager',
            field=models.ManyToManyField(blank=True, to='store.Manager'),
        ),
    ]
