# Generated by Django 2.0.5 on 2018-07-12 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20180712_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='expired_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='started_at',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
