# Generated by Django 2.0.5 on 2018-07-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20180712_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beacon',
            old_name='beaconId',
            new_name='beacon_id',
        ),
    ]
